# Generated by Django 5.2.17 on 2026-08-15 08:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_room_subject"),
        ("faculty", "0001_initial"),
        ("students", "0002_alter_student_options_student_department_and_more"),
        ("timetable", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "session_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="6-char code generated at session start.",
                        max_length=6,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Students can mark attendance from this time.",
                        null=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Attendance window closes at this time.",
                        null=True,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="Duration of the attendance window in minutes.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_attendance_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="faculty.faculty",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_sessions",
                        to="academics.room",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="academics.section",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="academics.subject",
                    ),
                ),
                (
                    "timetable_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_sessions",
                        to="timetable.timetableentry",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_sessions",
                "ordering": ["-date", "-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EXCUSED", "Excused"),
                        ],
                        db_index=True,
                        default="PRESENT",
                        max_length=20,
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("FACE_GPS", "Face + GPS"),
                            ("FACE", "Face Only"),
                            ("GPS", "GPS Only"),
                            ("MANUAL", "Manual Override"),
                            ("EXEMPT", "Exempted"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                ("face_verified", models.BooleanField(default=False)),
                ("gps_verified", models.BooleanField(default=False)),
                ("marked_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for ABSENT or EXCUSED status.",
                        max_length=250,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = student self-marked; set = faculty/admin override.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manually_marked_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="students.student",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="attendance.attendancesession",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_records",
                "ordering": ["-marked_at"],
            },
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["faculty", "date"], name="attendance__faculty_fb932f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["section", "date"], name="attendance__section_a3f057_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesession",
            index=models.Index(
                fields=["status", "date"], name="attendance__status_2a3930_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["session", "status"], name="attendance__session_523367_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["student", "session"], name="attendance__student_25f375_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("session", "student")},
        ),
    ]
