# Generated by Django 5.2.17 on 2026-08-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="liveness_verified",
            field=models.BooleanField(
                default=False,
                help_text="True if the student passed the liveness challenge (Phase 11).",
            ),
        ),
    ]
