# Generated by Django 5.2.17 on 2026-08-15 09:06

import apps.face.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0002_alter_student_options_student_department_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Clear frontal face photo (JPEG/PNG, min 200×200px).",
                        upload_to=apps.face.models.enrollment_upload_path,
                    ),
                ),
                (
                    "embedding",
                    models.JSONField(
                        blank=True,
                        help_text="Face embedding vector (512-d ArcFace). Null until processing succeeds.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Processing"),
                            ("ACTIVE", "Active"),
                            ("FAILED", "Processing Failed"),
                            ("REVOKED", "Revoked by Admin"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_enrollment",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "face_enrollments",
                "ordering": ["-created_at"],
            },
        ),
    ]
