# Generated by Django 5.2.17 on 2026-08-15 14:27

import django.db.models.deletion
import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("face", "0001_initial"),
        ("students", "0002_alter_student_options_student_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LivenessChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("BLINK", "Blink"),
                            ("NOD", "Nod your head"),
                            ("TURN_LEFT", "Turn head left"),
                            ("TURN_RIGHT", "Turn head right"),
                        ],
                        default="BLINK",
                        max_length=20,
                    ),
                ),
                (
                    "nonce",
                    models.CharField(
                        default=secrets.token_hex,
                        help_text="Random 32-byte hex nonce. Single-use; prevents response replay.",
                        max_length=64,
                    ),
                ),
                (
                    "session_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Attendance session code challenge was requested for.",
                        max_length=6,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Challenge expires 60s after creation."
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="True after the verify endpoint processes this challenge (pass or fail).",
                    ),
                ),
                (
                    "liveness_verified",
                    models.BooleanField(
                        help_text="Null=pending, True=passed, False=failed.", null=True
                    ),
                ),
                ("variance", models.FloatField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("frames_analyzed", models.IntegerField(blank=True, null=True)),
                ("faces_detected", models.IntegerField(blank=True, null=True)),
                ("fail_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liveness_challenges",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "face_liveness_challenges",
                "ordering": ["-created_at"],
            },
        ),
    ]
