# Generated by Django 5.2.17 on 2026-08-21 07:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("STUDENT_APPROVED", "Student Approved"),
                            ("STUDENT_REJECTED", "Student Rejected"),
                            ("ATTENDANCE_CORRECTION", "Attendance Correction"),
                            ("ROLE_CHANGE", "Role Change"),
                            ("SUBJECT_CHANGE", "Subject Change"),
                            ("TIMETABLE_CHANGE", "Timetable Change"),
                            ("SECURITY_EVENT", "Security Event"),
                            ("SUSPICIOUS_ATTEMPT", "Suspicious Attempt"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="audit_audit_event_t_ac78f0_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="audit_audit_actor_i_ec0f72_idx",
                    ),
                    models.Index(
                        fields=["severity", "created_at"],
                        name="audit_audit_severit_effc12_idx",
                    ),
                ],
            },
        ),
    ]
