# Generated by Django 5.2.17 on 2026-08-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('TRANSFERRED', 'Transferred'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=20),
        ),
    ]
