# Generated by Django 5.2.17 on 2026-08-14 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'CS-101', 'Lab-3', 'Seminar Hall'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("building", models.CharField(blank=True, max_length=100)),
                (
                    "floor",
                    models.SmallIntegerField(
                        default=0, help_text="0 = ground floor, negative = basement"
                    ),
                ),
                ("capacity", models.PositiveSmallIntegerField(default=60)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Center latitude of the room/building (WGS84).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Center longitude of the room/building (WGS84).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "geofence_radius",
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text="Geofence radius in meters. Students must be within this range to mark attendance.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("UNDER_MAINTENANCE", "Under Maintenance"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rooms",
                "ordering": ["building", "name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Subject code, e.g. 'CS301', 'MA201'.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("credits", models.PositiveSmallIntegerField(default=3)),
                (
                    "hours_per_week",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="Number of lecture hours per week."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "db_table": "subjects",
                "ordering": ["department", "code"],
                "unique_together": {("department", "name")},
            },
        ),
    ]
