# Generated by Django 5.2.17 on 2026-08-22 13:15

import datetime
from django.db import migrations


def seed_academic_years(apps, schema_editor):
    AcademicYear = apps.get_model('academics', 'AcademicYear')
    years = [
        ("2023-24", datetime.date(2023, 7, 1), datetime.date(2024, 6, 30), False),
        ("2024-25", datetime.date(2024, 7, 1), datetime.date(2025, 6, 30), True),
        ("2025-26", datetime.date(2025, 7, 1), datetime.date(2026, 6, 30), False),
        ("2026-27", datetime.date(2026, 7, 1), datetime.date(2027, 6, 30), False),
    ]
    for label, start, end, current in years:
        if not AcademicYear.objects.filter(label=label).exists():
            AcademicYear.objects.create(
                label=label,
                start_date=start,
                end_date=end,
                is_current=current
            )


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_room_subject'),
    ]

    operations = [
        migrations.RunPython(seed_academic_years),
    ]
