# Generated by Django 5.2.17 on 2026-08-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_student_options_student_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("SUSPENDED", "Suspended"),
                    ("COMPLETED", "Completed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
